version: "3.9"
services:
  client:
    build: ./client
    ports: ["5173:5173"]
    volumes: ["./client:/app"]
    environment:
      - VITE_API_URL=http://localhost:8000

  server:
    build: ./server
    ports: ["8000:8000"]
    volumes: ["./server:/app"]
    depends_on: [mongo]

  mongo:
    image: mongo
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

volumes:
  mongo_data:
